server:
  port: 9911
spring:
  application:
    name: users-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
management:
  context-path: /management