server:
  port: 9909
eureka:
  instance:
    hostname: configServer
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: register-server:9999/eureka
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vicykie/spring-boot-config-server

