server:
  port: 9999
spring:
  application:
    name: register-server
  cloud:
    config:
      uri: http://localhost:8888
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
